### PR TITLE
Fixes #110 

### LINKED ISSUE #110: Show the most voted time slot on the poll page
The poll creator could be 'shown' the time slot with the most votes to help them chose the final time. Feel free to come up with ideas on how to 'show'!

### PR DESCRIPTION
**Pull request by namansamra**
sample
desktop view final

### CODE REVIEW

**Comment by AnandBaburajan** [comment]
Thanks @namansamra! LGTM! A few suggestions: please take care of all the ESLint warnings/error [here](https://github.com/RocketMeet/RocketMeet-client/pull/119/files). Next time onwards, make sure to create a new branch for every new PR.

@VipinVIP and @iamAravindks please check after the warnings/errors are fixed and let us know your suggestions. Thanks!

**Comment by namansamra** [comment]
@AnandBaburajan  I have removed most of the ES lint errors that could be possibly removed. Kindly check and those errors which I am unable to remove are property of object , if you could share your comments it will be helpful.

**Comment by AnandBaburajan** [comment]
@VipinVIP PTAL, thanks. :)

**Comment by VipinVIP** [comment]
- **Unexpected any. Specify a different type**

    In case of errors like this , you can define a type ( in case its not basic types ) for the object/item 


- **Unexpected dangling '_' in '_meta'**

    For this error , you could add/change the **no-underscore-dangle**  in the eslint config file 

- **Assignment to property of function parameter 'event'** _( line 62 in src/components/poll/Chart.tsx)_

     This can also be turned off by disabling the eslint rule , but im not sure we should really do this in this case. maybe @AnandBaburajan  can help.

-  **Do not use Array index in keys** _(line 86 in src/components/poll/PollTable.tsx)_

     It is a bad practice to use array index as keys , even though it looks the most apt one in first look.

    > When you use index of an array as a key, React will optimize and not render as expected. What happens in such a scenario can be explained with an example.
</br>Suppose the parent component gets an array of 10 items and renders 10 components based on the array. Suppose the 5th item is then removed from the array. On the next render the parent will receive an array of 9 items and so React will render 9 components. This will show up as the 10th component getting removed, instead of the 5th, because React has no way of differentiating between the items based on index.
</br>Therefore always use a unique identifier as a key for components that are rendered from an array of items.
</br>You can generate your own unique key by using any of the field of the child object that is unique as a key. Normal, any id field of the child object can be used if available.

**Comment by namansamra** [comment]
@VipinVIP  
1. I have fixed the errors of dangling and parameter 'event' .
2. I tried to fix the 'any' type warning but it become worse so I remove them and also the type definition of the library used are not defined properly.

**Comment by AnandBaburajan** [comment]
Hey @namansamra! Can you rebase the PR and make the required changes? Thanks!

**Comment by AnandBaburajan** [comment]
Thank you @namansamra for your contribution! : )

**Pull request closed without merging**
