### PR TITLE
Added Dark Mode Button

### PR DESCRIPTION
**Pull request by manishprivet**
I added a Dark Mode button for #56 

Right now, I am having problems regarding the UI design of the button and I need some help with it.

For now, this button can be used to toggle CSS variables in the root element and persisting data in the local storage, as discussed in #56.

Can someone let me know if there are any design guidelines/Figma link that I should follow on designing the button?

### CODE REVIEW

**Comment by AnandBaburajan** [comment]
> Can someone let me know if there are any design guidelines/Figma link that I should follow on designing the button?

We don't have any design guidelines unfortunately. Would you like to suggest something? The button could be an icon right? Maybe this https://icons.getbootstrap.com/icons/sun-fill/ and the Moon for the dark mode?

**Comment by AnandBaburajan** [comment]
Also, please check your code after linting. You can simply setup automatic linting in vscode too.

**Comment by AnandBaburajan** [comment]
@VipinVIP I'm assigning you to look over this feature and assist Manish with doubts/suggestions. Thanks to both of you!

**Review by VipinVIP — COMMENTED** [review]
I just checked out the work you did . Since its work in progress , i recommend you to continue adding changes and pushing it. 😇

**Comment by manishprivet** [comment]
Thanks @VipinVIP @AnandBaburajan .

Yeah, it's unfinished work right now, and I'll push more changes to it, starting with changing that button to an icon.

**Comment by AnandBaburajan** [comment]
Closing this since we would need to rework on this when we move to Tailwind, but thank you @manishprivet!

**Pull request closed without merging**
